### ISSUE TITLE
Couple of confusing elements with the avatar in the update-user-data branch

### ISSUE THREAD

**Issue by dc453** [zachBridges/vue-exercises#3]
The avatar handling has a couple of misleading issues in the update-user-data branch.

1) There is no mention of the avatar in the Acceptance Criteria. Expectations should be provided of how the user avatar needs to function and display.

2) There was confusion on the instructions on not using an absolute path for the avatar in the Implementation Details. The test data has an external URL so absolute path seems to be the only thing possible unless you are expecting the developer to save the image to the repo itself. Clarification here would help.

**Comment by zachBridges** [comment]
![](
![image](https://user-images.githubusercontent.com/6400537/51403758-6b524280-1b1f-11e9-810d-ae007ca02baa.png)
)
You're absolutely right!

1. I was going to remove the avatar and forgot to. Joel made the point that the avatar detracts from the exercise.

2. The idea was to have the user practice and reinforce what they learned in the branch, background-image-static-site, regarding using require() to get an image asset in the script of a component and use it in their template. 

The fix is to just remove the avatar portion of this exercise. I'll get to that ASAP. 

Thanks, friendo

**Comment by zachBridges** [comment]
Updated in https://github.com/zachBridges/vue-exercises/pull/4
